class_name_mapping = {
    0: "Professor",
    1: "Estudar",
    2: "Aluno",
    3: "Dúvida",
    4: "Perguntar",
    5: "Responder",
    6: "Entender",
    7: "Pesquisar",
    8: "Aprender",
    9: "Quadro",
    10: "Prova",
    11: "Trabalho",
    12: "Computador",
    13: "Internet",
    14: "Tecnologia",
    15: "Algoritmo",
    16: "Inteligência Artificial",
    17: "Software",
    18: "Código",
    19: "Compilador",
}
